"""Inital commit-rename-chunk-id

Revision ID: e86b1245f91d
Revises: f1458315c1da
Create Date: 2026-07-21 17:37:46.064694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86b1245f91d'
down_revision: Union[str, Sequence[str], None] = 'f1458315c1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('chunks', sa.Column('chunk_uuid', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('chunk_uuid_key'), 'chunks', type_='unique')
    op.create_unique_constraint(None, 'chunks', ['chunk_uuid'])
    op.drop_column('chunks', 'chunk_uuid')
    op.drop_column('chunks', 'chunk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('chunks', sa.Column('chunk_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chunks', type_='unique')
    op.create_unique_constraint(op.f('chunks_uuid_key'), 'chunks', ['chunk_uuid'], postgresql_nulls_not_distinct=False)
    op.drop_column('chunks', 'chunk_uuid')
    op.drop_column('chunks', 'chunk_id')
    # ### end Alembic commands ###
